//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controls
{
    public partial class GameCard
    {
        /// <summary>
        /// lblCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCategory;

        /// <summary>
        /// lblDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDiscount;

        /// <summary>
        /// lnkBuy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBuy;

        /// <summary>
        /// lnkRent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkRent;
    }
}
