//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controls
{
    public partial class PricingCard
    {
        /// <summary>
        /// lnkCtaPrimary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkCtaPrimary;

        /// <summary>
        /// lnkCtaGhost control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkCtaGhost;
    }
}
