//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controls
{
    public partial class StoreButton
    {
        /// <summary>
        /// lnkButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkButton;

        /// <summary>
        /// btnAction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAction;
    }
}
