//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controls
{
    public partial class StoreInput
    {
        /// <summary>
        /// txtInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtInput;
    }
}
