//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class Buy
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litNavCartCount;
        protected global::System.Web.UI.WebControls.Literal litNavUsername;
        protected global::System.Web.UI.WebControls.HyperLink lnkSignOut;
        protected global::System.Web.UI.WebControls.Panel pnlCheckoutForm;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedPayment;
        protected global::System.Web.UI.WebControls.TextBox txtDeliveryEmail;
        protected global::System.Web.UI.WebControls.DropDownList ddlPlatform;
        protected global::System.Web.UI.WebControls.CheckBox chkAgree;
        protected global::System.Web.UI.WebControls.PlaceHolder phSingleItem;
        protected global::System.Web.UI.WebControls.Image imgSingleGame;
        protected global::System.Web.UI.WebControls.Literal litSingleTitle;
        protected global::System.Web.UI.WebControls.Label lblSingleTypeBadge;
        protected global::System.Web.UI.WebControls.Literal litSinglePlatform;
        protected global::System.Web.UI.WebControls.Literal litSinglePrice;
        protected global::System.Web.UI.WebControls.PlaceHolder phCartItems;
        protected global::System.Web.UI.WebControls.Repeater rptCartSummary;
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Panel pnlDiscountRow;
        protected global::System.Web.UI.WebControls.Literal litDiscount;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Button btnConfirmPurchase;
        protected global::System.Web.UI.WebControls.Panel pnlOrderSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccessEmail;
        protected global::System.Web.UI.WebControls.Literal litOrderId;
        protected global::System.Web.UI.WebControls.Repeater rptKeys;
        protected global::WebApplication1.Controls.SiteFooter siteFooter;
    }
}
