//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class Cart
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litNavCartCount;
        protected global::System.Web.UI.WebControls.Literal litNavUsername;
        protected global::System.Web.UI.WebControls.HyperLink lnkSignOut;
        protected global::System.Web.UI.WebControls.Literal litHeaderCount;
        protected global::System.Web.UI.WebControls.Panel pnlActiveCart;
        protected global::System.Web.UI.WebControls.Repeater rptCartItems;
        protected global::System.Web.UI.WebControls.LinkButton btnClearCart;
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Panel pnlDiscountRow;
        protected global::System.Web.UI.WebControls.Literal litDiscount;
        protected global::System.Web.UI.WebControls.TextBox txtPromo;
        protected global::System.Web.UI.WebControls.Button btnApplyPromo;
        protected global::System.Web.UI.WebControls.Label lblPromoFeedback;
        protected global::System.Web.UI.WebControls.Literal litGrandTotal;
        protected global::System.Web.UI.WebControls.HyperLink btnProceedToBuy;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;
        protected global::WebApplication1.Controls.SiteFooter siteFooter;
    }
}
