//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class Home
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litCartCount;
        protected global::System.Web.UI.WebControls.Literal litUsername;
        protected global::System.Web.UI.WebControls.HyperLink lnkSignOut;
        protected global::System.Web.UI.WebControls.Literal litHeroUser;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.HyperLink tabAll;
        protected global::System.Web.UI.WebControls.HyperLink tabAction;
        protected global::System.Web.UI.WebControls.HyperLink tabFantasy;
        protected global::System.Web.UI.WebControls.HyperLink tabMech;
        protected global::System.Web.UI.WebControls.HyperLink tabRacing;
        protected global::System.Web.UI.WebControls.Repeater rptGames;
        protected global::WebApplication1.Controls.SiteFooter siteFooter;
    }
}
